version: '3'
services:
  server:
    build: server/
    volumes:
      - .:/usr/src/app
    container_name: docker-node-server
    restart: always
    ports:
      - 3000:3000
  
  client:
    build: client/
    volumes:
      - .:/usr/src/app
    container_name: docker-node-client
    restart: always
    ports:
      - 4000:4000